/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import Transporte.AlgoritmoTransporte;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;

public class JFrameTransporte extends javax.swing.JFrame {

    AlgoritmoTransporte met=new AlgoritmoTransporte();
    DefaultTableModel origenModel;
    DefaultTableModel destinoModel;
    /**
     * Creates new form JFrameTransporte
     */
    public JFrameTransporte() {
        initComponents();
        this.setLocationRelativeTo(null);
        origenModel=(DefaultTableModel)tbDestino.getModel();
        destinoModel=(DefaultTableModel)tbOrigen.getModel();
    }
    private void bloquearKeyPress(Component a,boolean isLetter){
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PIngresarDatos = new javax.swing.JPanel();
        TPIngresarDatos = new javax.swing.JTabbedPane();
        POferta = new javax.swing.JPanel();
        SPOrigen = new javax.swing.JScrollPane();
        tbOrigen = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txtOfertaTotal = new javax.swing.JTextField();
        PDemanda = new javax.swing.JPanel();
        SPDestino = new javax.swing.JScrollPane();
        tbDestino = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        txtDemandaTotal = new javax.swing.JTextField();
        lblOrigen = new javax.swing.JLabel();
        txtOrigen = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtDestino = new javax.swing.JTextField();
        btnHabilitar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnResolver = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Método del Transporte");

        PIngresarDatos.setBorder(javax.swing.BorderFactory.createTitledBorder("Ingresar Datos"));

        TPIngresarDatos.setEnabled(false);

        tbOrigen.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Origenes", "Cantidad"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbOrigen.setEnabled(false);
        tbOrigen.getTableHeader().setReorderingAllowed(false);
        SPOrigen.setViewportView(tbOrigen);
        if (tbOrigen.getColumnModel().getColumnCount() > 0) {
            tbOrigen.getColumnModel().getColumn(0).setResizable(false);
            tbOrigen.getColumnModel().getColumn(1).setResizable(false);
        }

        jLabel1.setText("Oferta Total:");

        txtOfertaTotal.setEditable(false);

        javax.swing.GroupLayout POfertaLayout = new javax.swing.GroupLayout(POferta);
        POferta.setLayout(POfertaLayout);
        POfertaLayout.setHorizontalGroup(
            POfertaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(SPOrigen, javax.swing.GroupLayout.DEFAULT_SIZE, 396, Short.MAX_VALUE)
            .addGroup(POfertaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtOfertaTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        POfertaLayout.setVerticalGroup(
            POfertaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(POfertaLayout.createSequentialGroup()
                .addComponent(SPOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(POfertaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtOfertaTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        TPIngresarDatos.addTab("Ingresar Cantidades Ofertadas", POferta);

        tbDestino.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Destinos", "Cantidad"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbDestino.setEnabled(false);
        tbDestino.getTableHeader().setReorderingAllowed(false);
        SPDestino.setViewportView(tbDestino);
        if (tbDestino.getColumnModel().getColumnCount() > 0) {
            tbDestino.getColumnModel().getColumn(0).setResizable(false);
            tbDestino.getColumnModel().getColumn(1).setResizable(false);
        }

        jLabel2.setText("Demanda Total:");

        txtDemandaTotal.setEditable(false);

        javax.swing.GroupLayout PDemandaLayout = new javax.swing.GroupLayout(PDemanda);
        PDemanda.setLayout(PDemandaLayout);
        PDemandaLayout.setHorizontalGroup(
            PDemandaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(SPDestino, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(PDemandaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtDemandaTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(172, Short.MAX_VALUE))
        );
        PDemandaLayout.setVerticalGroup(
            PDemandaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PDemandaLayout.createSequentialGroup()
                .addComponent(SPDestino, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addGroup(PDemandaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtDemandaTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        TPIngresarDatos.addTab("Ingresar Cantidades Demandas", PDemanda);

        lblOrigen.setText("Número de Fabricas:");

        jLabel5.setText("Número de Clientes:");

        btnHabilitar.setText("Habilitar");
        btnHabilitar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHabilitarActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");

        btnResolver.setText("Resolver");

        javax.swing.GroupLayout PIngresarDatosLayout = new javax.swing.GroupLayout(PIngresarDatos);
        PIngresarDatos.setLayout(PIngresarDatosLayout);
        PIngresarDatosLayout.setHorizontalGroup(
            PIngresarDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PIngresarDatosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PIngresarDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PIngresarDatosLayout.createSequentialGroup()
                        .addComponent(lblOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDestino, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnHabilitar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TPIngresarDatos)
                    .addGroup(PIngresarDatosLayout.createSequentialGroup()
                        .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnResolver, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        PIngresarDatosLayout.setVerticalGroup(
            PIngresarDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PIngresarDatosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PIngresarDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblOrigen)
                    .addComponent(txtOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(txtDestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnHabilitar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TPIngresarDatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addGroup(PIngresarDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelar)
                    .addComponent(btnResolver))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PIngresarDatos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PIngresarDatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void modificarEtiquetas(int destino, int origen){
        int opcion=JOptionPane.showOptionDialog(this, "¿Desea ingresar el nombre de los puntos de origen y los puntos de destino?\nSí selecciona \"NO\" se pondrán números en su lugar","Método de Transporte",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE,null,new Object[]{"SI","NO"},"SI");
        String dato;
        int numero;
        if(opcion==0){
            while(origenModel.getRowCount()>0)
                origenModel.removeRow(0);
            while(destinoModel.getRowCount()>0)
                destinoModel.removeRow(0);
            for(int i=0;i<origen;i++){
                dato=JOptionPane.showInputDialog(this,"Ingrese el nombre del Origen "+(i+1),JOptionPane.INFORMATION_MESSAGE);
                numero=Integer.parseInt(JOptionPane.showInputDialog(this,"Ingrese la cantidad ofertada en "+dato,JOptionPane.INFORMATION_MESSAGE));
                origenModel.addRow(new Object[]{dato,numero});
            }
            for(int i=0;i<destino;i++){
                dato=JOptionPane.showInputDialog(this,"Ingrese el nombre del destino "+(i+1),JOptionPane.INFORMATION_MESSAGE);
                numero=Integer.parseInt(JOptionPane.showInputDialog(this,"Ingrese la cantidad demandada en "+dato,JOptionPane.INFORMATION_MESSAGE));
                destinoModel.addRow(new Object[]{dato,numero});
            }
        }
        else{
            while(origenModel.getRowCount()>0)
                origenModel.removeRow(0);
            while(destinoModel.getRowCount()>0)
                destinoModel.removeRow(0);
            for(int i=0;i<origen;i++){
                numero=Integer.parseInt(JOptionPane.showInputDialog(this,"Ingrese la cantidad ofertada en "+(i+1),JOptionPane.INFORMATION_MESSAGE));
                origenModel.addRow(new Object[]{i+1,numero});
            }
            for(int i=0;i<destino;i++){
                numero=Integer.parseInt(JOptionPane.showInputDialog(this,"Ingrese la cantidad demandada en "+(i+1),JOptionPane.INFORMATION_MESSAGE));
                destinoModel.addRow(new Object[]{i+1,numero});
            }
        }
    }
    private void btnHabilitarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHabilitarActionPerformed
        // TODO add your handling code here:
        JFrameTransporte jfram=new JFrameTransporte();
        String origen=txtOrigen.getText(), destino=txtDestino.getText();
        if(!origen.isEmpty()){
            if(!destino.isEmpty()){
                met.setOrigem(Integer.parseInt(origen));
                met.setDestino(Integer.parseInt(destino));
                TPIngresarDatos.setEnabled(true);
                tbDestino.setEnabled(true);
                tbOrigen.setEnabled(true);
                modificarEtiquetas(Integer.parseInt(destino),Integer.parseInt(origen));
            }
            else
                JOptionPane.showMessageDialog(this, "Debe ingresar la la cantidad de puntos de destino de sus productos ","Campos Vacíos",JOptionPane.INFORMATION_MESSAGE);
        }else{
            JOptionPane.showMessageDialog(this, "Debe ingresar la la cantidad de puntos de origen de sus productos ","Campos Vacíos",JOptionPane.INFORMATION_MESSAGE);
        }
        
    }//GEN-LAST:event_btnHabilitarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            javax.swing.UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameTransporte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameTransporte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameTransporte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameTransporte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameTransporte().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PDemanda;
    private javax.swing.JPanel PIngresarDatos;
    private javax.swing.JPanel POferta;
    private javax.swing.JScrollPane SPDestino;
    private javax.swing.JScrollPane SPOrigen;
    private javax.swing.JTabbedPane TPIngresarDatos;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnHabilitar;
    private javax.swing.JButton btnResolver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel lblOrigen;
    private javax.swing.JTable tbDestino;
    private javax.swing.JTable tbOrigen;
    private javax.swing.JTextField txtDemandaTotal;
    private javax.swing.JTextField txtDestino;
    private javax.swing.JTextField txtOfertaTotal;
    private javax.swing.JTextField txtOrigen;
    // End of variables declaration//GEN-END:variables
}
